export enum Groups {
  CREATE = 'CREATE',
  READ = 'READ',
  QUERY = 'QUERY',
  SIGNUP = 'SIGNUP',
  JOIN_TEAM = 'JOIN_TEAM',
  TIMESTAMP = 'TIMESTAMP',
  PASSWORD = 'PASSWORD',
  AUTH_COOKIE = 'AUTH_COOKIE',
  CREDENTIALS = 'CREDENTIALS',
}
