/**
 * Configuration keys used accross the application
 */
export enum ConfigEnum {
  // Server
  PUBLIC_DIR = 'PUBLIC_DIR',
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',

  // AUTH
  JWT_SECRET = 'JWT_SECRET',

  // database
  DB_MAIN_NAME = 'DB_NAME',
  DB_CLIENT_NAME = 'DB_CLIENT_NAME',
  DB_ADMIN_NAME = 'DB_ADMIN_NAME',

  DB_TYPE = 'DB_TYPE',

  DB_ADMIN_USERNAME = 'DB_ADMIN_USERNAME',
  DB_ADMIN_PASSWORD = 'DB_ADMIN_PASSWORD',

  DB_CLIENT_USERNAME = 'DB_CLIENT_USERNAME',
  DB_CLIENT_PASSWORD = 'DB_CLIENT_PASSWORD',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
}
