import { trim } from 'lodash';

/**
 * create a pipable collection method that split string by x and trim each
 * @param delimeter
 * @returns
 */
export function splitBy(delimeter: string) {
  return (value: string) => value.split(delimeter).map(trim);
}

/**
 * Genereate a number of items whose instance is generated by the passed generator function
 * @param generator
 * @param times
 * @returns { T[] } Array<T>
 */
export function mapTimes<T = any>(generator: () => T, times: number) {
  return '_'.repeat(times).split('').map(generator);
}
